project_name: nsc
release:
  github:
    owner: nats-io
    name: nsc
  name_template: '{{.Tag}}'
  draft: true
builds:
- id: nsc
  main: ./main.go
  ldflags: "-X main.version={{.Tag}}"
  env:
    - CGO_ENABLED=0
  binary: nsc
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64

dist: build

archives:
  - id: "nsc.zip"
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: zip
    files:
      - none*

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: 'dev'


brews:
  - name: nsc
    folder: Formula
    github:
      owner: nats-io
      name: homebrew-nats-tools
    url_template: "https://github.com/nats-io/nsc/releases/download/{{ .Tag }}/nsc-{{ .Os }}-{{ .Arch }}.zip"
    homepage: "https://github.com/nats-io/nsc"
    description: "A tool for creating NATS account and user access configurations"
    skip_upload: false
    test: |
      system "#{bin}/nsc --version"
    install: |
      bin.install "nsc"



